use crate::ai::agent::SuggestedLoggingId;
use crate::drive::items::{ai_fact::LocalDriveAIFact, LocalDriveItem};
use crate::object_store::ids::ObjectStoreId;
use crate::{
    drive::ObjectTypeAndId,
    object_store::{
        model::{
            generic_string_model::{GenericStringModel, GenericStringObjectId, StringModel},
            json_model::{JsonModel, JsonSerializer},
        },
        GenericStoredObject, GenericStringObjectFormat, GenericStringObjectUniqueKey,
        JsonObjectType,
    },
};
use serde::{Deserialize, Serialize};
use warp_core::ui::appearance::Appearance;

pub mod manager;
pub mod view;
pub use manager::AIFactManager;
pub use view::{AIFactView, AIFactViewEvent};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AIFact {
    #[serde(rename = "memory")]
    Memory(AIMemory),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AIMemory {
    #[serde(default)]
    pub name: Option<String>,
    pub content: String,
    // Deprecated: This field is no longer used and will be removed in the future.
    #[serde(default)]
    pub is_autogenerated: bool,
    /// If this rule was created from a suggested rule, record the suggestion's logging_id
    /// so we can suppress re-surfacing the same suggestion in future responses.
    #[serde(default)]
    pub suggested_logging_id: Option<SuggestedLoggingId>,
}

impl AIFact {
    pub fn is_memory(&self) -> bool {
        matches!(self, AIFact::Memory { .. })
    }
}

pub type AIFactObject = GenericStoredObject<GenericStringObjectId, AIFactObjectModel>;
pub type AIFactObjectModel = GenericStringModel<AIFact, JsonSerializer>;

impl StringModel for AIFact {
    type StoredObjectType = AIFactObject;

    fn model_type_name(&self) -> &'static str {
        "Rule"
    }

    fn should_enforce_revisions() -> bool {
        true
    }

    fn model_format() -> GenericStringObjectFormat {
        GenericStringObjectFormat::Json(JsonObjectType::AIFact)
    }

    fn should_show_activity_toasts() -> bool {
        true
    }

    fn warn_if_unsaved_at_quit() -> bool {
        true
    }

    fn display_name(&self) -> String {
        match self {
            AIFact::Memory(memory) => memory.content.clone(),
        }
    }

    fn uniqueness_key(&self) -> Option<GenericStringObjectUniqueKey> {
        None
    }

    fn renders_in_local_drive(&self) -> bool {
        false
    }

    fn to_local_drive_item(
        &self,
        id: ObjectStoreId,
        _appearance: &Appearance,
        ai_fact: &AIFactObject,
    ) -> Option<Box<dyn LocalDriveItem>> {
        Some(Box::new(LocalDriveAIFact::new(
            ObjectTypeAndId::GenericStringObject {
                object_type: GenericStringObjectFormat::Json(JsonObjectType::AIFact),
                id,
            },
            ai_fact.clone(),
        )))
    }
}

impl JsonModel for AIFact {
    fn json_object_type() -> JsonObjectType {
        JsonObjectType::AIFact
    }
}
